version: '3.3'
services:
  requestrr:
    container_name: requestrr
    ports:
      - 4545:4545 # The web UI will be accessible at the address: requestrr:7878
    volumes:
      - /your/path/to/your/requestrr/config:/root/config # Path to where your persistent requestrr data will be stored.
    restart: unless-stopped
    image: darkalfx/requestrr
    networks:
      - your_network_name_here # Change this to the network you created for your automation containers.

networks:
  your_network_name_here: # Change this to the network you created for your automation containers.
    external: true
