---
version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000 # Change this to your host OS users UID.
      - PGID=1000 # Change this to your host OS users GID.
      - TZ=Europe/London # Update this to your local timezone in TZ database format.
    volumes:
      - /your/path/to/your/prowlarr/config:/config # Path to where your persistent Prowlarr data will be stored.
    ports:
      - 9696:9696  # The web UI will be accessible at the address: prowlarr:9696
    restart: unless-stopped
    networks:
      - your_network_name_here # Change this to the network you created for your automation containers.

networks:
  your_network_name_here: # Change this to the network you created for your automation containers.
    external: true
